version: "3.7"
services:
  app-masamura:
    container_name: app-masamura
    image: node:16.14.0
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      npm run build"
    tty: true
  web-masamura:
    container_name: web-masamura
    image: nginx:latest
    ports:
      - 3050:80
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - "app"
    tty: true
